trigger:
  branches:
    include:
      - main # Trigger on changes to the main branch

resources:
  repositories:
    - repository: MyBlogRepo
      type: github
      name: aarohisp/MyBlog
      endpoint: GitHub-Connection

variables:
  # AKS variables
  ACR_NAME: "mernblogregistry"
  RESOURCE_GROUP: "Mern_blog"
  AKS_CLUSTER: "MernBlog"
  IMAGE_NAME: "myblog-static-site"
  DEPLOYMENT_COLOR: "blue" # Change to "green" during demonstration

  # Tag with color for blue-green
  TAG: "deploy-$(DEPLOYMENT_COLOR)-$(Build.BuildId)"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Package
    displayName: "Package Static Files"
    jobs:
      - job: PackageFiles
        displayName: "Package HTML/CSS/JS into a Container Image"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 0 # Full repository history for consistent builds

          - script: |
              echo "Starting Dockerfile creation for static site..."
              echo "FROM nginx:alpine" > Dockerfile
              echo "COPY src/index.html /usr/share/nginx/html/" >> Dockerfile
              echo "COPY src/style.css /usr/share/nginx/html/" >> Dockerfile
              echo "COPY src/script.js /usr/share/nginx/html/" >> Dockerfile
            displayName: "Create Dockerfile for Static Site"

          - task: AzureCLI@2
            displayName: "Build and Push to Azure Container Registry"
            inputs:
              azureSubscription: "azure-connection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr login --name $(ACR_NAME)
                az acr build --registry $(ACR_NAME) --image $(IMAGE_NAME):$(TAG) -f "$(Build.SourcesDirectory)/Dockerfile" .

  - stage: Deploy
    dependsOn: Package
    displayName: "Deploy to AKS"
    jobs:
      - job: DeployToAKS
        displayName: "Deploy Static Site to AKS"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureCLI@2
            displayName: "Login to AKS Cluster"
            inputs:
              azureSubscription: "azure-connection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER)
                echo "Logged into AKS cluster."

          # Echo out image names for debugging
          - script: |
              echo "Using image: $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)"
            displayName: "Echo Image for Deployment"

          - task: KubernetesManifest@0
            displayName: "Apply Blue-Green Deployment"
            inputs:
              kubernetesServiceConnection: "kubernetes-connection"
              action: "deploy"
              namespace: "default"
              manifests: "manifests/deployment.yaml" # Same file, dynamic image reference
              containers: |
                $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)
            env:
              DEPLOYMENT_COLOR: "$(DEPLOYMENT_COLOR)" # Used for manifest templating if needed

          - script: |
              echo "Deployment completed for $(DEPLOYMENT_COLOR)."
            displayName: "Deployment Confirmation"
