apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog-static-site
      version: $(DEPLOYMENT_COLOR)
  template:
    metadata:
      labels:
        app: myblog-static-site
        version: $(DEPLOYMENT_COLOR)
    spec:
      containers:
        - name: nginx-container
          image: mernblogregistry.azurecr.io/myblog-static-site:$(DEPLOYMENT_COLOR)-${TAG}
          ports:
            - containerPort: 80
