apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog-$(DEPLOYMENT_COLOR)
  labels:
    app: myblog-$(DEPLOYMENT_COLOR)
spec:
  selector:
    matchLabels:
      app: myblog-$(DEPLOYMENT_COLOR)
  template:
    metadata:
      labels:
        app: myblog-$(DEPLOYMENT_COLOR)
    spec:
      containers:
      - name: myblog-container
        image: $(ACR_NAME).azurecr.io/$(IMAGE_NAME):deploy-$(TAG)
