apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog-static-site
      version: blue # Label to distinguish blue version
  template:
    metadata:
      labels:
        app: myblog-static-site
        version: blue
    spec:
      containers:
        - name: nginx-container
          image: mernblogregistry.azurecr.io/myblog-static-site:blue-${TAG}

          ports:
            - containerPort: 80
